<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;
use AppBundle\Entity\Competitor;
use AppBundle\Entity\Race;
use AppBundle\Entity\Championship;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * ChampionshipCompetitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionshipCompetitorRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return boolean
     */
    public function competitorIsRegisterToChampionship(Championship $championship, Competitor $competitor)
    {
        return $this->findOneBy(array('championship' => $championship->getId(), 'competitor' => $competitor->getId()));

    }
}
