<?php

namespace AppBundle\Repository;


use AppBundle\Entity\Competitor;

/**
 * CompetitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitorRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Competitor $competitor
     * @return Race|array
     * contains array competitor data
     *
     */
    public function toString(Competitor $competitor)
    {
        $c = $this->createQueryBuilder('c')
            ->select('c.firstName,c.lastName,c.date')
            ->where('c.id = :id')
            ->setParameter('id', $competitor->getId())
            ->getQuery()->getResult();

        return $c[0];
    }

    public function firstAll($nb)
    {
        $c = $this->createQueryBuilder('c')
            ->where('c.id <= :nb')
            ->setParameter('nb', $nb)
            ->getQuery()->getResult();

        return $c;
    }

    public function nextRace($competitor)
    {
        $date = date('Y-m-d H:i:s', strtotime('now'));

        $rawSql = "SELECT r.id, r.date_time FROM race_competitor rc
                   INNER JOIN competitor c on rc.competitor_id = c.id
                   INNER JOIN race r on rc.race_id = r.id
                   WHERE c.id = " . $competitor . "
                   AND r.date_time > '" . $date . "'
                   ORDER BY r.date_time
                   LIMIT 1";

        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute([]);

        return $stmt->fetch();
    }
}
