<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Dev;
use Doctrine\ORM\Query\ResultSetMapping;


/**
 * DevRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevRepository extends \Doctrine\ORM\EntityRepository
{

    public function removeAllCompetitions()
    {
        $rsm = new ResultSetMapping();


        $query = $this->createNativeNamedQuery( 'DELETE FROM race_category;
                                                            DELETE FROM race_championship;
                                                            DELETE FROM championship_competitor;
                                                            DELETE FROM race_competitor;
                                                            DELETE FROM race;
                                                            DELETE FROM competition;
                                                            DELETE FROM location;
                                                            
                                                            ALTER TABLE race_category AUTO_INCREMENT=0;
                                                            ALTER TABLE race_championship AUTO_INCREMENT=0;
                                                            ALTER TABLE championship_competitor AUTO_INCREMENT=0;
                                                            ALTER TABLE race AUTO_INCREMENT=0;
                                                            ALTER TABLE race_competitor AUTO_INCREMENT=0;
                                                            ALTER TABLE location AUTO_INCREMENT=0;
                                                            ALTER TABLE competition AUTO_INCREMENT=0;');

        return $query->getResult();
    }

}
