<?php

namespace AppBundle\Repository;


/**
 * RaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceRepository extends \Doctrine\ORM\EntityRepository
{

    public function lastId($class)
    {
        return $this->createQueryBuilder('a')
            ->select('MAX(e.id)')
            ->from('AppBundle:' . $class, 'e')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function toString()
    {
        $races = $this->createQueryBuilder('r')
            ->innerJoin('r.competition', 'c')
            //->select('r.code, r.name, r.dateString, r.inChampionship, c.code')
            ->select('r.id, r.name, r.dateTime')
            ->getQuery()->getResult();

        for ($i = 0; $i < count($races); $i++) {
            $races[$i]['checkbox'] = '';
            $races[$i]['date'] = date_format($races[$i]['dateTime'], 'd-m-Y');;
        }

        return $races;
    }

}
