<?php

namespace AppBundle\Repository;

/**
 * RaceCompetitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceCompetitorRepository extends \Doctrine\ORM\EntityRepository
{

}
